### ISSUE TITLE
Confirm TF model input/output format from Fumin

### ISSUE THREAD

**Issue by bearprada** [plant-tw/PlantsCam-Android#5]
*Inputs*

* `agent/img` : [1,128,128,3] Float
* `agent/len_pixel` : [1] Float
* `agent/len_cm` : [1] Float

*Output*

* `agent/Softmax`: [1,N] Float

N means number of classes we provide

**Comment by bearprada** [comment]
Question for @fumin what's the pixel order for input image?

1.  [r1, g1, b1, r2, g2, b2, r3, g3, b3, r4, g4, b4]
2.  [r1, r2, r3, r4, g1, g2, g3, g4, b1, b2, b3, b4]

or ??

**Comment by fumin** [comment]
Umm, there’s really no pixel order, as the shape of the image tensor is explicit.
The interpretation of the dimensions in the shape [1, 128, 128, 3] is:

1: batch size, no specific meaning during inference
128: height of image
128: width of image
3: red, blue, and green channels of the image

**Comment by fumin** [comment]
Ah, I just read the comment in Messenger.
I think the problem might be that the values here are normalised between 0 and 1.
In other words, we need to divide the uint8 values by 255.

**Comment by bearprada** [comment]
we will try @x4base for the first version, so I close this PR
